### ISSUE TITLE
Partial feedback

### ISSUE THREAD

**Issue by cynic** [BenTrope/Morabaraba#1]
I had some muuuuuuch longer feedback, and then someone changed the name of this repository and the feedback died during submission.  Oh well!  I leave you with this function, which should help a bit:

```fsharp
let output board =
    //printfn "%A" board
    let v pos =
        let idx =
            List.findIndex ((=) pos)
                [ "a1";"a4";"a7";"d7";"g7";"g4";"g1";"d1"
                  "b2";"b4";"b6";"d6";"f6";"f4";"f2";"d2"
                  "c3";"c4";"c5";"d5";"e5";"e4";"e3";"d3"
                ]
        match List.item idx board with
        | 0 -> 'O'
        | 1 -> 'R'
        | 2 -> 'B'
        | n ->
            sprintf "Internal state corrupt, received %d; dying." n
            |> failwith
    printfn """
       1  2  3  4  5  6  7
    A  %c--------%c--------%c
       |\\      |      //|
    B  |  %c-----%c-----%c  |
       |  |\\   |   //|  |
    C  |  |  %c--%c--%c  |  |
       |  |  |     |  |  |
    D  %c--%c--%c     %c--%c--%c
       |  |  |     |  |  |
    E  |  |  %c--%c--%c  |  |
       |  |//   |   \\|  |
    F  |  %c-----%c-----%c  |
       |//      |      \\|
    G  %c--------%c--------%c
    """ (v "a1") (v "a4") (v "a7") (v "b2") (v "b4") (v "b6") (v "c3") (v "c4") (v "c5")
        (v "d1") (v "d2") (v "d3") (v "d5") (v "d6") (v "d7")
        (v "e3") (v "e4") (v "e5") (v "f2") (v "f4") (v "f6") (v "g1") (v "g4") (v "g7")
```
You already know the major issues: you can replace one cow with another, you can move your opponent's cows, there's no mill detection, there's no end-of-game detection.  There's too much that's missing for me to allocate a very good mark.  If you had better data structures, things might be easier for you to develop.

Feel free to hit me, or your tutors, up on Slack with questions - we're here to help!

**Comment by edg3** [comment]
We will be working on this later today and will get in touch if we have any questions.

**Comment by Tiaan-H** [comment]
As a team we sorted out most of the move sets and board, we have most of the features implemented.
